apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
data:
  config.yaml: |
    config_items:
    - repos:
      - ascend
      commits_threshold: 1

    - repos:
      - ascend/canndev
      - ascend/cann_op_contrib
      - ascend/ACLLite
      - ascend/EdgeAndRobotics
      - ascend/torchair
      - ascend/vision
      - ascend/Asight
      - ascend/metadef
      - ascend/parser
      - ascend/tensorflow
      - ascend/ascend-faster-transformer
      - ascend/ascend-inference-ptplugin
      - ascend/ascend-devkit-imager
      - ascend/ascend-devkit-model-adapter
      - ascend/ascend-transformer-acceleration
      - ascend/ascend-op-common-lib
      - ascend/ascend-inference
      - ascend/att
      commits_threshold: 1
      clear_labels:
      - ci-pipeline-passed
